### ISSUE TITLE
encounter RuntimeError: unmatched '}' in format string when training for fixed-timestep interpolation

### ISSUE THREAD

**Issue by 108062138** [MCG-NJU/EMA-VFI#10]
As title,  I meet `RuntimeError: unmatched '}' in format string` when I want to train the model by my own.  I wonder if there exists a way to by pass this error.
After typing the command `  python -m torch.distributed.launch --nproc_per_node=4 train.py --world_size 4 --batch_size 8 --data_path **YOUR_VIMEO_DATASET_PATH** `(I did edit the dataset path), I get the following output in my terminal 
```javascript=
Traceback (most recent call last):
...
File "C:\anaconda3\envs\tf2.5\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
File "C:\anaconda3\envs\tf2.5\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: unmatched '}' in format string
```

My environment: pytorch 1.13.1+cu117/python 3.8.15/win 10

**Comment by GuozhenZhang1999** [comment]
We have encountered no associated errors in our recommended environment configuration. Hopefully you can run it in the current recommended configuration.
