### ISSUE TITLE
This error occurs when I train to the last batch_size of epoch2. Is there a problem with the data set? Should this path (/sequences//im3.png) contain images

### ISSUE THREAD

**Issue by lucy0427** [MCG-NJU/EMA-VFI#17]
[ WARN:0@6340.512] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('./vimeo_triplet/sequences//im1.png'): can't open/read file: check file path/integrity
[ WARN:0@6340.512] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('./vimeo_triplet/sequences//im2.png'): can't open/read file: check file path/integrity
[ WARN:0@6340.512] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('./vimeo_triplet/sequences//im3.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    train(model, args.local_rank, args.batch_size, args.data_path)
  File "train.py", line 62, in train
    evaluate(model, val_data, nr_eval, local_rank)
  File "train.py", line 74, in evaluate
    for _, imgs in enumerate(val_data):
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wan/EMA-VFI-main/dataset.py", line 89, in __getitem__
    img0 = torch.from_numpy(img0.copy()).permute(2, 0, 1)
AttributeError: 'NoneType' object has no attribute 'copy'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 894631) of binary: /home/wan/anaconda3/envs/vif/bin/python
Traceback (most recent call last):
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wan/anaconda3/envs/vif/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-01_10:31:16
  host      : auto
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 894631)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by lucy0427** [comment]
Okay, I solved that problem.

**Comment by vokkko** [comment]
> Okay, I solved that problem.
how to solve this problem? I meet the same situation. : (

**Comment by vokkko** [comment]
I change the batch_sie to 16 when i train the model used 2 gpus, but  i met this question. Thus I tried to train the model for using 4 gpus with setting 8 batch_size. However it still wrong! How can i fix this problem?

**Comment by Plumess** [comment]
> I change the batch_sie to 16 when i train the model used 2 gpus, but i met this question. Thus I tried to train the model for using 4 gpus with setting 8 batch_size. However it still wrong! How can i fix this problem?

Maybe the path is wrong because the last line of the vimeo_triplet dataset path list has a blank line, because “imread_('. /vimeo_triplet/sequences//im1.png'): can't open/read file: check file path/integrity", the // there should be a path.

**Comment by yilonghe** [comment]
How to solve this problem? I meet the same situation.

**Comment by yilonghe** [comment]
How to solve this problem? I meet the same situation.   ( CUDA_VISIBLE_DEVICES=1 torchrun --nproc_per_node=1 train.py --world_size=1 --batch_size=4 --data_path=/home/xh/Downloads/vimeo_triplet )  epoch:2 3206/3207 time:0.00+0.37 loss:4.5710e-02
[ WARN:0@3594.568] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/xh/Downloads/vimeo_triplet/sequences//im1.png'): can't open/read file: check file path/integrity
[ WARN:0@3594.568] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/xh/Downloads/vimeo_triplet/sequences//im2.png'): can't open/read file: check file path/integrity
[ WARN:0@3594.568] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('/home/xh/Downloads/vimeo_triplet/sequences//im3.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
