### ISSUE TITLE
ROCm support

### ISSUE THREAD

**Issue by TyraVex** [MCG-NJU/EMA-VFI#5]
Hello,

Is it possible to use EMA-VFI with ROCm and an AMD GPU?

```
python3.9 demo_2x.py 
Traceback (most recent call last):
  File "/home/tyra/Downloads/EMA-VFI/demo_2x.py", line 36, in <module>
    model = Model(-1)
  File "/home/tyra/Downloads/EMA-VFI/Trainer.py", line 17, in __init__
    self.device()
  File "/home/tyra/Downloads/EMA-VFI/Trainer.py", line 32, in device
    self.net.to(torch.device("cuda"))
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/tyra/Downloads/EMA-VFI/env/lib/python3.9/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by GuozhenZhang1999** [comment]
Although we haven't tried it ourselves, the official website indicates that Pytorch 1.8 supports AMD. You can refer to the official instructions for more information.

**Comment by TyraVex** [comment]
Thanks, i'll dig into it and provide some instructions if I succeed

**Comment by TyraVex** [comment]
Ok, so after a lot of trouble I got the demo to work on arch linux, with a rx 5700.

First I installed rocm. That was a long time ago, i don't remember the exact packages, but here is what I have on my system :
```
hsa-amd-aqlprofile-bin
rocm-opencl-runtime
rocm-device-libs
rocminfo
```

After this, the GPU appears after executing /opt/rocm/bin/rocminfo 
```
*******                  
Agent 2                  
*******                  
  Name:                    gfx1010                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 5700       
  ```
  
 Then, i cloned this repo and created a virtual env with python 3.8
 pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2
 pip install scikit-image==0.19.2 numpy==1.23.1 opencv-python==4.6.0.66 timm==0.6.11 tqdm
 (Note : I tried every version from 1.8 without success, but all I missed was a version override before executing python, so I ended up with pytorch 2, which surprisingly works)
 
 Finally, I downloaded the weights under ./cktp/ and ran HSA_OVERRIDE_GFX_VERSION=10.3.0 python demo_2x.py

**Comment by TyraVex** [comment]
Turns out after further testing this works better (for my setup at least)
pip install torch==1.12.0+rocm5.1.1 torchvision==0.13.0+rocm5.1.1 torchaudio==0.12.0 --extra-index-url  https://download.pytorch.org/whl/rocm5.1.1
Note : you will also need ncurses5-compat-libs (yay -S  ncurses5-compat-libs) for this version to work.
